parameters:
- name: image
  type: string
  default: 'windows-latest'
  values:
  - 'windows-latest'
  - 'ubuntu-latest'
- name: workers
  type: number
- name: parallelism
  type: number
- name: pool
  displayName: Target Pool
  type: string
- name: azureRegion
  type: string
  default: '*'
  values:
  - '*'
  - westus
  - eastus
  - northcentralus
- name: jobName
  type: string

jobs:
- ${{ if ne(parameters.workers, 0) }}:
  - job: ${{ parameters.jobName }}
    pool: server
    steps:
    - task: InvokeRESTAPI@1
      name: ${{ parameters.jobName }}
      inputs:
        connectionType: 'connectedServiceName'
        serviceConnection: 'GitHubAgents'
        method: 'POST'
        body: |
          {
            "ref": "main",
            "inputs": {
              "buildNumber": "$(Build.DefinitionName) - $(Build.BuildNumber) - $(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)",
              "jobCount": ${{ parameters.workers }},
              "parallelism": ${{ parameters.parallelism }},
              "pool": "${{ parameters.pool }}",
              "image": "${{ parameters.image }}",
              "targetAzureRegion": "${{ replace(parameters.azureRegion, '*', '') }}",
              "token": "$(System.AccessToken)",
              "taskUrl": "$(System.CollectionUri)$(System.TeamProject)?buildId=$(Build.BuildId)&jobId=$(System.JobId)&planId=$(System.PlanId)&taskId=$(System.TaskInstanceId)&timelineId=$(System.TimelineId)"
            }
          }
        urlSuffix: '$(Agents_Request_Url)'
        waitForCompletion: 'true'
        timeoutInMinutes: 5