name: RunnerDispatch
run-name: "Agents for ${{ inputs.buildNumber }}"
on:
  workflow_dispatch:
    inputs:
      runnerIds:
        description: "List of comma separated integer ids for the runners."
        required: true
        default: "1, 2"
      buildNumber:
        description: "The requesting pipeline build number."
        required: true
        default: "unknown"
      image:
        description: "The vm image to run the agent with."
        required: true
        default: "windows-latest"
      pool:
        description: "The pool to add the agent."
        required: true
      agentName:
        description: "The name of the agent."
        required: false
        default: ''
      url:
        description: "The organization url to use for the agent."
        required: false
        default: ''
      token:
        description: "The token to use for the agent."
        required: false
        default: ''
      operationId:
          description: "The operation ID to identify agents."
          required: false
          default: 'unspecified'
jobs:
  build:
    strategy:
      matrix:
        runnerId: ${{ fromJSON(format('[{0}]', inputs.runnerIds)) }}
    runs-on: ${{ inputs.image }}
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v2"
      - name: "Run PowerShell script"
        shell: pwsh
        env:
          AZP_URL: ${{ secrets.AZP_URL }}
          AZP_AGENT_NAME: ${{ inputs.agentName }}
          AZP_TOKEN: ${{ inputs.token != '' && inputs.token || secrets.AZP_TOKEN }}
          AZP_POOL: ${{ inputs.pool }}
          # AZP_WORK: "C:/azdev/agent"
          Capability.OperationId: ${{ inputs.operationId }}
          Capability.Image: ${{ inputs.image }}
        run: |
          Get-ChildItem Env:
          ./startup.ps1
