on:
  workflow_call:
    inputs:
      jobCount:
        description: "List of comma separated integer ids for the runners."
        required: true
        type: number
      jobIndex:
        description: "The requesting pipeline build number."
        required: true
        type: number
jobs:
  0a:
    if: ${{ inputs.jobIndex < inputs.jobCount }}
    runs-on: ubuntu-latest
    steps:
      - name: "Run Agent"
        shell: pwsh
        run: |
          Write-Host ${{ inputs.jobIndex }}
