on:
  workflow_call:
    outputs:
      hasmorejobs: 
        value: ${{ jobs.run.outputs.hasmorejobs }}
    inputs:
      env:
        description: "Input environment."
        type: string
        default: '{}'
      message:
        description: "Message."
        type: string
        default: '{}'

env: ${{ fromJson(inputs.env) }}

jobs:
  run:
    outputs:
      hasmorejobs: ${{ steps.run.outputs.hasmorejobs }}
    runs-on: ${{ fromJSON(inputs.env).image }}
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v2"
      - name: "Reserve and setup state"
        id: setup
        shell: pwsh
        run: |
          $inputMessage = @'
          ${{ inputs.message }}
          '@
          Write-Host "Message: $inputMessage"

          $azureRegion = Invoke-RestMethod -Headers @{"Metadata"="true"} -Uri "http://169.254.169.254/metadata/instance/compute/location?api-version=2017-08-01&format=text"
          Write-Host "Azure Region: $azureRegion"

          $Env:AzureRegion = $azureRegion

          if ($Env:targetAzureRegion -and ($Env:targetAzureRegion -ne $azureRegion)) {
            exit 0;
          }

          . dotnet tools/AzDevAgentRunner.dll reserve --taskUrl "${{ env.taskUrl }}" --token "${{ env.token }}" --jobCount ${{ env.jobCount }}
          exit 0;
      - name: "Run Agent (IsReserved=${{ steps.setup.outputs.isReserved }})"
        id: run
        shell: pwsh
        env:
          AZP_TASK_URL: ${{ env.taskUrl }}
          AZP_POOL: ${{ env.pool }}
          Capability.Image: ${{ env.image }}
        run: |
          if (-not $Env:AZP_URL) {
            . dotnet tools/AzDevAgentRunner.dll reserve --taskUrl "${{ env.taskUrl }}" --token "${{ env.token }}" --jobCount ${{ env.jobCount }} --checkOnly
            exit 0;
          }

          Get-ChildItem Env:
          ./startup.ps1
    