name: TestMatrix
run-name: "Agents for ${{ inputs.buildNumber }}"
on:
  workflow_dispatch:
    inputs:
      jobCount:
        description: "List of comma separated integer ids for the runners."
        required: true
        default: 1
        type: number
      parallelism:
        description: "The requesting pipeline build number."
        required: true
        default: 2
        type: number
      image:
        description: "The vm image to run the agent with."
        required: true
        default: "ubuntu-latest"

env:
  parallelism: ${{ fromJSON(inputs.parallelism) < fromJSON(inputs.jobCount) && fromJSON(inputs.parallelism) || fromJSON(inputs.jobCount)  }}
  threadsIds: "[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]"

jobs:
  stage:
    strategy:
      max-parallel: ${{ fromJSON(env.parallelism) }}
      matrix:
        threadIndex: [0,1,2,3]
    uses: ./.github/workflows/testmatrix.thread.yml
    secrets: inherit
    with:
      env: ${{ toJSON(inputs) }}
      parallelism: ${{ fromJSON(inputs.parallelism) }}
      jobIndex: ${{ strategy.job-index }}