on:
  workflow_call:
    inputs:
      env:
        description: "Input environment."
        type: string
        default: '{}'
      jobIndex:
        description: "The requesting pipeline build number."
        required: true
        type: number
    outputs:
      stopjobthread: ${{ jobs.run.outputs.stopjobthread }}

env: ${{ fromJson(inputs.env) }}

jobs:
  run:
    if: ${{ inputs.jobIndex < inputs.jobCount }}
    runs-on: ubuntu-latest
    steps:
      - name: "Reserve and Run Agent"
        shell: pwsh
        run: |
          echo "stobjobthread=true" >> $Env:GITHUB_OUTPUT
