on:
  workflow_call:
    inputs:
      jobIndex:
        description: "The requesting pipeline build number."
        required: true
        type: number
      parallelism:
        description: "The requesting pipeline build number."
        required: true
        default: 2
        type: number
      env:
        description: "Input environment."
        type: string
        default: '{}'
jobs:
  start:
    strategy:
      max-parallel: 1
      matrix:
        threadIndex: [0,1,2]
    steps:
    - id: runstep
      name: "Reserve and Run Agent"
      env:
        AZP_URL: ${{ secrets.AZP_URL }}
        Capability_Image: ${{ env.image }}
      shell: pwsh
      run: |
        $needs = @'
          ${{ toJSON(jobs) }}
        '@
        echo "needs=$needs"
        echo "hasmorejobs=false" >> $Env:GITHUB_OUTPUT
        Get-ChildItem Env:
  job0:
    needs: start
    if: ${{ inputs.jobIndex < inputs.parallelism }}
    uses: ./.github/workflows/testmatrix.job.yml
    secrets: inherit
    with:
      env: ${{ inputs.env }}
  job1:
    needs: job0
    if: ${{ contains(needs.*.outputs.hasmorejobs, 'true') }}
    uses: ./.github/workflows/testmatrix.job.yml
    with:
      env: ${{ inputs.env }}
  job2:
    needs: job1
    if: ${{ contains(needs.*.outputs.hasmorejobs, 'true') }}
    uses: ./.github/workflows/testmatrix.job.yml
    with:
      env: ${{ inputs.env }}