name: TestMatrix
run-name: "Agents for ${{ inputs.buildNumber }}"
on:
  workflow_dispatch:
    inputs:
      jobCount:
        description: "List of comma separated integer ids for the runners."
        required: true
        default: 1
        type: number
      parallelism:
        description: "The requesting pipeline build number."
        required: true
        default: 10
        type: number
jobs:
  build:
    strategy:
      matrix:
        d0: [0,1,2,3,4,5,6,7,8,9]
        d1: [0,1]
    uses: ./.github/workflows/testmatrix.job.yml
    with:
      jobCount: 1
      jobIndex: ${{ strategy.job-index }}