on:
  workflow_call:
    outputs:
      hasmorejobs: 
        value: ${{ jobs.run.outputs.hasmorejobs }}
    inputs:
      env:
        description: "Input environment."
        type: string
        default: '{}'

env: ${{ fromJson(inputs.env) }}

jobs:
  run:
    outputs:
      hasmorejobs: ${{ steps.runstep.outputs.hasmorejobs }}
    runs-on: ${{ fromJSON(inputs.env).image }}
    steps:
      - id: runstep
        name: "Reserve and Run Agent"
        shell: pwsh
        run: |
          $needs = @'
            ${{ env.parallelism }}
            ${{ secrets.AZP_URL }}
          '@
          echo "needs=$needs"
          echo "hasmorejobs=false" >> $Env:GITHUB_OUTPUT
          Get-ChildItem Env:
    