on:
  workflow_call:
    outputs:
      stopjobthread: 
        value: ${{ jobs.run.outputs.stopjobthread }}
    inputs:
      env:
        description: "Input environment."
        type: string
        default: '{}'
      jobCount:
        description: "The requesting pipeline build number."
        required: true
        type: number

env: ${{ fromJson(inputs.env) }}

jobs:
  run:
    outputs:
      stopjobthread: ${{ steps.runstep.output.stobjobthread }}
    runs-on: ubuntu-latest
    steps:
      - id: runstep
        name: "Reserve and Run Agent"
        shell: pwsh
        run: |
          echo "stobjobthread=false" >> $Env:GITHUB_OUTPUT
    