on:
  workflow_call:
    outputs:
      hasmorejobs: 
        value: ${{ jobs.run.outputs.hasmorejobs }}
    inputs:
      env:
        description: "Input environment."
        type: string
        default: '{}'
      needs:
        description: "Needs value."
        type: string
        default: '{}'
      jobCount:
        description: "The requesting pipeline build number."
        required: true
        type: number

env: ${{ fromJson(inputs.env) }}

jobs:
  run:
    outputs:
      hasmorejobs: ${{ steps.runstep.output.hasmorejobs }}
    runs-on: ubuntu-latest
    steps:
      - id: runstep
        name: "Reserve and Run Agent"
        shell: pwsh
        env:
          NEEDS: ${{ inputs.needs }}
        run: |
          echo "hasmorejobs=false" >> $Env:GITHUB_OUTPUT
          Get-ChildItem Env:
    